### ISSUE TITLE
Use immutable image and server profile github tags

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/Customer360#4]
'sup.

Please can the docker-compose please use immutable image tags (pingidentity/pingfederate:2006-10.1.0) and server profile github repo tags (use of SERVER_PROFILE_BRANCH environment variable)?

This is so C360 Releases don't break and degrade over time after new image/server profile updates are made

**Comment by cprice-ping** [comment]
This current release of Product highlights this problem - I'll publish a v2.0 soon that handles the new versions. 

Ideally, this solution is current with :latest - but that requires dedicated resources - pinning the C360 versions to known, working, versions makes sense
