### ISSUE TITLE
PD 8.1 now requires 768m max heap environment variable

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/Customer360#5]
'sup

PD 8.1 images (now on latest tag) now require an environment variable MAX_HEAP_SIZE >= 768m.  Without this PD startup fails and manual changes are required

Please can this be included?

**Comment by cprice-ping** [comment]
It'll be fixed when I merge my V2.0 branch

**Comment by cprice-ping** [comment]
I just merged in a new version -- the env-vars file contains this variable.
