### ISSUE TITLE
PingDirectory (pdAdminURL) incorrect in Postman Collection

### ISSUE THREAD

**Issue by joelrader-ping** [pingidentity/Customer360#6]
I believe it's supposed to be:
https://{{PD_HOSTNAME}}:8443/console

It's shown instead as https://pingdirectory:443, which doesn't match up to the DataConsole port (8443).

**Comment by cprice-ping** [comment]
DataConsole is a separate service - it doesn't run on PD

**Comment by joelrader-ping** [comment]
On this page: https://github.com/pingidentity/Customer360/tree/master/deployment

Listed: pdAdminUrl | PingDir Administration URL | https://pingdirectory:443

Shouldn't the pdAdminUrl be listed as https://{hostname}:8443/console? It appears to be a typo. There's nothing on 443 for an admin console.

**Comment by cprice-ping** [comment]
No - this is for Postman to connect to the PD ConfigAPI Admin endpoint.

Anything in the `postman_vars.json` is to drive the environment variables into the initial API calls -- nothing to do with what happens after the calls are completed.
